make github action more explicit on failure

diff --git a/.github/workflows/tree-validation.yml b/.github/workflows/tree-validation.yml
--- a/.github/workflows/tree-validation.yml
+++ b/.github/workflows/tree-validation.yml
@@ -43,4 +43,6 @@ jobs:
 
     - name: Fail workflow if validation failed
       if: steps.validate-mappings.outcome == 'failure'
-      run: exit 1
+      run: |
+        echo "Mapping validation failed. See the 'Validate Mappings' step for more details."
+        exit 1
